### ISSUE TITLE
Can I return to the first image when I go over all images by using arrow

### ISSUE THREAD

**Issue by workinghoward** [CafeMap/react-flexible-carousel#22]
Hi, I like ur carousel component, it's great, but I think when I use arrow to the last image, 
it can reset the action ID to first one!
Thanks!

btw, it seems like I can not change the autoplay time when it initialized

**Comment by madeinfree** [comment]
@workinghoward Yes, I can release this next version, Thanks !!

**Comment by madeinfree** [comment]
release in v1.2.5
